name: Two-Hour RSS Feed Update

on:
  schedule:
    # Run every 2 hours between 7:30 AM and 11:30 PM Pacific Time
    # PDT (UTC-7) hours: 14:30, 16:30, 18:30, 20:30, 22:30, 00:30, 02:30, 04:30, 06:30
    - cron: '30 14,16,18,20,22,0,2,4,6 * * *'
    # PST (UTC-8) hours: 15:30, 17:30, 19:30, 21:30, 23:30, 01:30, 03:30, 05:30, 07:30
    - cron: '30 15,17,19,21,23,1,3,5,7 * * *'
  workflow_dispatch:  # Allow manual triggering

# Add permissions needed to commit and push
permissions:
  contents: write

jobs:
  update-feed:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create output directory
      run: mkdir -p output
        
    - name: Run RSS feed generator
      run: python ark_full_feed.py
        
    - name: Debug - List files
      run: |
        echo "Current directory:"
        ls -la
        echo "Output directory:"
        ls -la output/ || echo "Output directory not found or empty"
      
    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "Update RSS feed - $(date)" || echo "No changes to commit"
        git push
