name: Two-Hour RSS Feed Update

on:
  schedule:
    # Run every 2 hours, with one run at 7:30 AM Pacific (14:30 UTC during PDT, 15:30 UTC during PST)
    # This handles both standard and daylight saving time
    - cron: '30 14,16,18,20,22,0,2,4,6,8,10,12 * * *'  # Every 2 hours starting at 14:30 UTC
    - cron: '30 15,17,19,21,23,1,3,5,7,9,11,13 * * *'  # Every 2 hours starting at 15:30 UTC
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-feed:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run RSS feed generator
      run: python ark_full_feed.py
      
    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add output/full_feed.xml
        git diff --quiet && git diff --staged --quiet || git commit -m "Update RSS feed - $(date)"
        git push
